accounts/urls.py
from django.conf.urls import url

from insuranceplans.views import UserInsuranceplanHistoryView
from .views import (
    AccountHomeView,
    AccountEmailActivateView,
    UserDetailUpdateView
)

urlpatterns = [
    url(r'^$', AccountHomeView.as_view(), name='home'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),
    url(r'^history/insuranceplans/$', UserInsuranceplanHistoryView.as_view(), name='user-insuranceplan-history'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name='email-activate'),
    url(r'^email/resend-activation/$', AccountEmailActivateView.as_view(), name='resend-activation'),
]

articles/urls.py
from django.urls import path
from articles import views

# from .forms import ArticleForm

urlpatterns = [
    path('details/<slug:slug>/', views.ArticleDetail.as_view(), name='article_detail'),
    path('', views.ArticleList.as_view(), name='article_list'),
]

carts/urls.py
from django.urls import path

from .views import (
        cart_home,
        cart_update,
        checkout_home,
        checkout_done_view
        )

urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/success/', checkout_done_view, name='success'),
    path('checkout/<int:pk>', checkout_home, name='checkout'),
    path('update/', cart_update, name='update'),
]

insuranceplans/urls.py
from django.conf.urls import url

from .views import (
        InsuranceplanListView,
        InsuranceplanDetailSlugView,
        InsuranceplanDownloadView
        )

urlpatterns = [
    url(r'^$', InsuranceplanListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', InsuranceplanDetailSlugView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/$', InsuranceplanDownloadView.as_view(), name='download'),
]

talisa/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include, re_path
from django.views.generic import RedirectView, TemplateView

from accounts.views import LoginView, GuestRegisterView, RegisterView
from addresses.views import AddressListView, AddressCreateView, AddressUpdateView, checkout_address_create_view, \
    checkout_address_reuse_view
from analytics.views import SalesView, SalesAjaxView
from billing.views import payment_method_view, payment_method_createview
from carts.views import cart_detail_api_view
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView
from orders.views import LibraryView
from talisa.views import home_page, about_page, contact_page


urlpatterns = [
    path('', home_page, name='home'),
    path('about/', about_page, name='about'),
    path('articles/', include(('articles.urls', 'articles'), namespace='articles')),

    path('accounts/', RedirectView.as_view(url='/account')),
    path('account/', include(('accounts.urls', 'account'), namespace='account')),
    path('accounts/', include("accounts.passwords.urls")),
    path('admin-Talisa-Ng/', admin.site.urls),

    path('login/', LoginView.as_view(), name='login'),
    path('register/guest/', GuestRegisterView.as_view(), name='guest_register'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
    url(r'^address/$', RedirectView.as_view(url='/addresses')),
    url(r'^addresses/$', AddressListView.as_view(), name='addresses'),
    url(r'^addresses/create/$', AddressCreateView.as_view(), name='address-create'),
    url(r'^addresses/(?P<pk>\d+)/$', AddressUpdateView.as_view(), name='address-update'),
    url(r'^analytics/sales/$', SalesView.as_view(), name='sales-analytics'),
    url(r'^analytics/sales/data/$', SalesAjaxView.as_view(), name='sales-analytics-data'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    url(r'^cart/', include(("carts.urls", 'cart'), namespace='cart')),
    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),
    url(r'^billing/payment-method/create/$', payment_method_createview, name='billing-payment-method-endpoint'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^library/$', LibraryView.as_view(), name='library'),
    url(r'^orders/', include(("orders.urls", 'orders'), namespace='orders')),
    url(r'^insuranceplans/', include(("insuranceplans.urls", 'insuranceplans'), namespace='insuranceplans')),
    # url(r'^search/', include("search.urls", namespace='search')),
    url(r'^settings/$', RedirectView.as_view(url='/account')),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^webhooks/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
]

# administrator backend service url
# urlpatterns += [
#     path('admin-Talisa-Ng/', admin.site.urls),
# ]

# url to catch any unmatch url for 404...
urlpatterns += [re_path(r'^.*', TemplateView.as_view(template_name='404.html'))]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

<!-- Fontawesome CSS -->
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />

<!-- jquery-confirm CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">


<!-- Custom Stripe Styling -->
<link rel="stylesheet" href="{% static 'css/stripe-custom-style.css' %}">

templates/base/forms.html
{% extends "base.html" %}


{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <button type='submit' class='btn btn-default'>Save</button>
</form>
</div>
{% endblock %}

templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS
slim is missing ajax -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
<!-- Stripe JS -->
<script src="https://js.stripe.com/v3/"></script>
<!-- jquery-confirm JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>
<!-- js Render -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.88/jsrender.min.js'></script>
{% include 'base/js_templates.html' %}


<!-- jQuery -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- jQuery Easing -->
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Waypoints -->
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<!-- Stellar Parallax -->
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<!-- Carousel -->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<!-- Flexslider -->
<script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
<!-- countTo -->
<script src="{% static 'js/jquery.countTo.js' %}"></script>
<!-- Magnific Popup -->
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/magnific-popup-options.js' %}"></script>
<!-- Sticky Kit -->
<script src="{% static 'js/sticky-kit.min.js' %}"></script>
<!-- Main -->
<script src="{% static 'js/main.js' %}"></script>
<!-- Chart.js -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js'></script>
<!-- Django Secure AJAX JS -->
<script src='{% static "js/csrf.ajax.js" %}'></script>

templates/base/js_templates.html
{% verbatim %}
<!-- stripe template form -->
<script id="stripeTemplate" type="text/x-jsrender">
    <form class='payment-form' action="" method="post" id="payment-form" data-token='{{:publishKey}}' data-next-url='{{:nextUrl}}'>
  <div class="form-row">
    <!-- <label for="card-element">
      Credit or debit card
    </label> -->
    <div id="card-element" class='form-control'> 
      <!-- a Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button class='btn btn-primary my-3 btn-load'>{{:btnTitle }}</button>

    </form>

</script>
{% endverbatim %}

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'articles:article_list' as article_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'insuranceplans:list' as insuranceplan_list_url %}
{% url 'account:home' as account_url %}
{% url 'cart:home' as cart_url %}
{% url '/admin-Talisa-Ng/' as admin_url %}


<div class="menu-wrap">
    <div class="container">
        <div class="row">
            <div class="col-xs-8">
                <div class="menu-1">
                    <ul>
                        <li class="{% if request.path == home_url %}active{% endif %}"><a href="{{ home_url }}">Home</a></li>
                        <li class="has-dropdown">
                            <a href="#">Company</a>
                            <ul class="dropdown">
                                <li><a href="#">About</a></li>
                                <li><a href="{{ contact_url }}">Contact</a></li>
                            </ul>
                        </li>
                        <li><a href="{{ insuranceplan_list_url }}">Plans</a></li>
                        {% if request.user.is_authenticated %}
                            <li class="has-dropdown">
                                <a href="{{ account_url }}" class="btn btn-primary btn-outline">Account</a>
                                <ul class="dropdown">
                                    <li>
                                        <a href="{{ account_url }}" class="{% if request.path == account_url %}active{% endif %}">
                                            Home
                                        </a>
                                    </li>
                                    <li><a href="{{ account_url }}#billing">Billing</a></li>
                                    <li><a href="{% url "account:user-insuranceplan-history" %}">History</a></li>
                                    <li><a href="{% url 'library' %}">Library</a></li>
                                    <li><a href="{{ logout_url }}">Logout</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li><a href="{{ register_url }}">Register</a></li>
                            <li><a href="{{ login_url }}">Login</a></li>
                        {% endif %}
                        {% if request.user.is_admin or equest.user.is_staff %}
                            <li><a href="/admin-Talisa-Ng/" class="btn btn-primary btn-outline">Admin</a></li>
                        {% endif %}
                        <li><a href="{{ article_url }}">Blog</a></li>
                        <li><a href="{{ cart_url }}">Cart</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>