accounts/passwords/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    url(r'^password/reset/$',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'),
    url(r'^password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
]

accounts/urls.py
from django.conf.urls import url

from insuranceplans.views import UserInsuranceplanHistoryView
from .views import (
    AccountHomeView,
    AccountEmailActivateView,
    UserDetailUpdateView
)

urlpatterns = [
    url(r'^$', AccountHomeView.as_view(), name='home'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),
    url(r'^history/insuranceplans/$', UserInsuranceplanHistoryView.as_view(), name='user-insuranceplan-history'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name='email-activate'),
    url(r'^email/resend-activation/$', AccountEmailActivateView.as_view(), name='resend-activation'),
]

carts/urls.py
from django.urls import path

from .views import (
        cart_home,
        cart_update,
        checkout_home,
        checkout_done_view
        )

urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/success/', checkout_done_view, name='success'),
    path('checkout/<int:pk>', checkout_home, name='checkout'),
    path('update/', cart_update, name='update'),
]

insuranceplans/urls.py
from django.conf.urls import url

from .views import (
        InsuranceplanListView,
        InsuranceplanDetailSlugView,
        InsuranceplanDownloadView
        )

urlpatterns = [
    url(r'^$', InsuranceplanListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', InsuranceplanDetailSlugView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/$', InsuranceplanDownloadView.as_view(), name='download'),
]

talisa/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include, re_path
from django.views.generic import RedirectView, TemplateView

from accounts.views import LoginView, GuestRegisterView, RegisterView
from addresses.views import AddressListView, AddressCreateView, AddressUpdateView, checkout_address_create_view, \
    checkout_address_reuse_view
from analytics.views import SalesView, SalesAjaxView
from billing.views import payment_method_view, payment_method_createview
from carts.views import cart_detail_api_view
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView
from orders.views import LibraryView
from talisa.views import home_page, about_page, contact_page


urlpatterns = [
    path('', home_page, name='home'),
    path('about/', about_page, name='about'),
    path('articles/', include(('articles.urls', 'articles'), namespace='articles')),

    path('accounts/', RedirectView.as_view(url='/account')),
    path('account/', include(('accounts.urls', 'account'), namespace='account')),
    path('accounts/', include("accounts.passwords.urls")),
    path('admin-Talisa-Ng/', admin.site.urls),

    path('login/', LoginView.as_view(), name='login'),
    path('register/guest/', GuestRegisterView.as_view(), name='guest_register'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
    url(r'^address/$', RedirectView.as_view(url='/addresses')),
    url(r'^addresses/$', AddressListView.as_view(), name='addresses'),
    url(r'^addresses/create/$', AddressCreateView.as_view(), name='address-create'),
    url(r'^addresses/(?P<pk>\d+)/$', AddressUpdateView.as_view(), name='address-update'),
    url(r'^analytics/sales/$', SalesView.as_view(), name='sales-analytics'),
    url(r'^analytics/sales/data/$', SalesAjaxView.as_view(), name='sales-analytics-data'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    url(r'^cart/', include(("carts.urls", 'cart'), namespace='cart')),
    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),
    url(r'^billing/payment-method/create/$', payment_method_createview, name='billing-payment-method-endpoint'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^library/$', LibraryView.as_view(), name='library'),
    url(r'^orders/', include(("orders.urls", 'orders'), namespace='orders')),
    url(r'^insuranceplans/', include(("insuranceplans.urls", 'insuranceplans'), namespace='insuranceplans')),
    # url(r'^search/', include("search.urls", namespace='search')),
    url(r'^settings/$', RedirectView.as_view(url='/account')),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^webhooks/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
]

# administrator backend service url
# urlpatterns += [
#     path('admin-Talisa-Ng/', admin.site.urls),
# ]

# url to catch any unmatch url for 404...
urlpatterns += [re_path(r'^.*', TemplateView.as_view(template_name='404.html'))]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.urls import reverse
from django.utils.safestring import mark_safe

User = get_user_model()

from .models import EmailActivation, GuestEmail


class ReactivateEmailForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = EmailActivation.objects.email_exists(email)
        if not qs.exists():
            register_link = reverse("register")
            msg = """This email does not exists, would you like to <a href="{link}">register</a>?
            """.format(link=register_link)
            raise forms.ValidationError(mark_safe(msg))
        return email


class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name', 'email',)  # 'full_name',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserDetailChangeForm(forms.ModelForm):
    full_name = forms.CharField(label='Name', required=False, widget=forms.TextInput(attrs={"class": 'form-control'}))

    class Meta:
        model = User
        fields = ['full_name']


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('full_name', 'email', 'password', 'is_active', 'admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class GuestForm(forms.ModelForm):
    # email    = forms.EmailField()
    class Meta:
        model = GuestEmail
        fields = [
            'email'
        ]

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(GuestForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        # Save the provided password in hashed format
        obj = super(GuestForm, self).save(commit=False)
        if commit:
            obj.save()
            request = self.request
            request.session['guest_email_id'] = obj.id
        return obj


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email')
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(LoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control mb'

    def clean(self):
        request = self.request
        data = self.cleaned_data
        email = data.get("email")
        password = data.get("password")
        qs = User.objects.filter(email=email)
        if qs.exists():
            # user email is registered, check active/
            not_active = qs.filter(is_active=False)
            if not_active.exists():
                ## not active, check email activation
                link = reverse("account:resend-activation")
                reconfirm_msg = """Go to <a href='{resend_link}'>
                resend confirmation email</a>.
                """.format(resend_link=link)
                confirm_email = EmailActivation.objects.filter(email=email)
                is_confirmable = confirm_email.confirmable().exists()
                if is_confirmable:
                    msg1 = "Please check your email to confirm your account or " + reconfirm_msg.lower()
                    raise forms.ValidationError(mark_safe(msg1))
                email_confirm_exists = EmailActivation.objects.email_exists(email).exists()
                if email_confirm_exists:
                    msg2 = "Email not confirmed. " + reconfirm_msg
                    raise forms.ValidationError(mark_safe(msg2))
                if not is_confirmable and not email_confirm_exists:
                    raise forms.ValidationError("This user is inactive.")
        user = authenticate(request, username=email, password=password)
        if user is None:
            raise forms.ValidationError("Invalid credentials")
        login(request, user)
        self.user = user
        return data


class RegisterForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name', 'email',)  # 'full_name',)

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control mb'

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = True  # send confirmation email via signals
        # obj = EmailActivation.objects.create(user=user)
        # obj.send_activation_email()
        if commit:
            user.save()
        return user

accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import Http404
from django.urls import reverse
from django.views.generic import CreateView, FormView, DetailView, View, UpdateView
from django.views.generic.edit import FormMixin
from django.shortcuts import render, redirect
from django.utils.safestring import mark_safe

from talisa.mixins import NextUrlMixin, RequestFormAttachMixin
from .forms import LoginForm, RegisterForm, GuestForm, ReactivateEmailForm, UserDetailChangeForm
from .models import EmailActivation
from .signals import user_logged_in


class AccountHomeView(LoginRequiredMixin, DetailView):
    template_name = 'accounts/home.html'

    def get_object(self):
        return self.request.user


class AccountEmailActivateView(FormMixin, View):
    success_url = '/login/'
    form_class = ReactivateEmailForm
    key = None

    def get(self, request, key=None, *args, **kwargs):
        self.key = key
        if key is not None:
            qs = EmailActivation.objects.filter(key__iexact=key)
            confirm_qs = qs.confirmable()
            if confirm_qs.count() == 1:
                obj = confirm_qs.first()
                obj.activate()
                messages.success(request, "Your email has been confirmed. Please login.")
                return redirect("login")
            else:
                activated_qs = qs.filter(activated=True)
                if activated_qs.exists():
                    reset_link = reverse("password_reset")
                    msg = """Your email has already been confirmed
                    Do you need to <a href="{link}">reset your password</a>?
                    """.format(link=reset_link)
                    messages.success(request, mark_safe(msg))
                    return redirect("login")
        context = {'form': self.get_form(), 'key': key}
        return render(request, 'registration/activation-error.html', context)

    def post(self, request, *args, **kwargs):
        # create form to receive an email
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        msg = """Activation link sent, please check your email."""
        request = self.request
        messages.success(request, msg)
        email = form.cleaned_data.get("email")
        obj = EmailActivation.objects.email_exists(email).first()
        user = obj.user
        new_activation = EmailActivation.objects.create(user=user, email=email)
        new_activation.send_activation()
        return super(AccountEmailActivateView, self).form_valid(form)

    def form_invalid(self, form):
        context = {'form': form, "key": self.key}
        return render(self.request, 'registration/activation-error.html', context)


class GuestRegisterView(NextUrlMixin, RequestFormAttachMixin, CreateView):
    form_class = GuestForm
    default_next = '/register/'

    def get_success_url(self):
        return self.get_next_url()

    def form_invalid(self, form):
        return redirect(self.default_next)


class LoginView(NextUrlMixin, RequestFormAttachMixin, FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'accounts/login.html'
    default_next = '/'

    def form_valid(self, form):
        next_path = self.get_next_url()
        return redirect(next_path)

    def render_to_response(self, context, **response_kwargs):
        if context:
            if self.request.user.is_authenticated:
                raise Http404
        return super(LoginView, self).render_to_response(context, **response_kwargs)


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = '/login/'

    def render_to_response(self, context, **response_kwargs):
        if context:
            if self.request.user.is_authenticated:
                raise Http404
        return super(RegisterView, self).render_to_response(context, **response_kwargs)


class UserDetailUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserDetailChangeForm
    template_name = 'accounts/detail-update-view.html'

    def get_object(self):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Change Your Account Details'
        return context

    def get_success_url(self):
        return reverse("account:home")

accounts/templates/accounts/detail-update-view.html
{% extends "base.html" %}
{% block navbar %} {% include 'base/navbar.html' %} {% endblock navbar %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class='col-12 col-md-6 mx-auto'>
                {% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
                <hr>
                <br>
                <form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
                    {% if next_url %}
                        <input type='hidden' name='next' value='{{ next_url }}' />
                    {% endif %}
                    {{ form.as_p }}
                    <label for='email'>Email</label>
                    <input type='text' id='email' class='form-control disabled' value='{{ request.user.email }}' disabled="disabled" /><span class='help-text'>Cannot change email</span><br/>
                    <hr>
                    <button type='submit' class='btn btn-default my-3'>Save</button>
                    <a href='{% url "password_change" %}'>Change Password</a>
                </form>
            </div>
        </div>
    </div>
    <br>
    <br>
{% endblock %}

accounts/templates/accounts/home.html
{% extends "base.html" %}

{% load static %}

{% block navbar %} {% include 'base/navbar.html' %} {% endblock navbar %}

{% block content %}

<div class="colorlib-loader"></div>

<div id="page">

        <aside id="colorlib-hero" class="breadcrumbs">
            <div class="flexslider">
                <ul class="slides">
                <li style="background-image: url({% static 'images/pulse-trace.jpg' %});">
                    <div class="overlay"></div>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2 col-md-pull-2 slider-text">
                                <div class="slider-text-inner">
                                    <h1>Name: {{ request.user.get_full_name }}</h1>
                                    <h2>Email: {{ request.user.email }}</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                </ul>
            </div>
        </aside>

    <div class="container">
        <div class='row'>

            <div class='col-12'>
                <h1>Account</h1>
                <hr/>
            </div>

            <div class="col-12 col-md-4 my-3 animate-box">
                <div class="blog-entry">
                    <a class="blog-img" style="background-image: url({% static 'images/anesthesia.jpg' %});"></a>
                    <div class="desc">
                        <h3>Support</h3>
                        <ul class="plan">
                            <li><span>About</span><span><a href='{% url "about" %}'><i class="icon-arrow-right3"></i></a></span></li>
                            <li><span>Contact</span><span><a href='{% url "contact" %}'><i class="icon-arrow-right3"></i></a></span></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-4 my-3 animate-box">
                <div class="blog-entry">
                    <a class="blog-img" style="background-image: url({% static 'images/blog-1.jpg' %});"></a>
                    <div class="desc">
                        <h3>Billing</h3>
                        <ul class="plan">
                            <li><span>Orders</span><span><a href='{% url "orders:list" %}'><i class="icon-arrow-right3"></i></a></span></li>
                            <li><span>Payment Methods</span><span><a href='{% url "billing-payment-method" %}'><i class="icon-arrow-right3"></i></a></span></li>
                            <li><span>Addresses</span><span><a href='{% url "addresses" %}'><i class="icon-arrow-right3"></i></a></span></li>
                        </ul>
                    </div>
                </div>
            </div>


            <div class="col-12 col-md-4 my-3 animate-box">
                <div class="blog-entry">
                    <a class="blog-img" style="background-image: url({% static 'images/medical-name.jpg' %});"></a>
                    <div class="desc">
                        <h3>Account Details</h3>
                        <ul class="plan">
                            <li><span>Update Details</span><span><a href='{% url "account:user-update" %}'><i class="icon-arrow-right3"></i></a></span></li>
                            <li><span>Change Password</span><span><a href='{% url "password_change" %}'><i class="icon-arrow-right3"></i></a></span></li>
                            <li><span>Library</span><span><a href='{% url "library" %}'><i class="icon-arrow-right3"></i></a></span></li>
                        </ul>
                    </div>
                </div>
            </div>


            <div class="col-12 col-md-4 my-3 animate-box">
                <div class="blog-entry">
                    <a class="blog-img" style="background-image: url({% static 'images/doctor123.jpg' %});"></a>
                    <div class="desc">
                        <h3>Preferences</h3>
                        <ul class="plan">
                            <li><span>Email Marketing</span><span><a href='{% url "marketing-pref" %}'><i class="icon-arrow-right3"></i></a></span></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-4 my-3 animate-box">
                <div class="blog-entry">
                    <a class="blog-img" style="background-image: url({% static 'images/hospital-ward.jpg' %});"></a>
                    <div class="desc">
                        <h3>History</h3>
                        <ul class="plan">
                            <li><span>Insurance Plans</span><span><a href='{% url "account:user-insuranceplan-history" %}'><i class="icon-arrow-right3"></i></a></span></li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>
    
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block navbar %} {% include 'base/navbar.html' %} {% endblock navbar %}

{% block content %}

    <div id="colorlib-contact">
		<div class="container">
			<div class="row">
                <div class="col-md-12 animate-box">
					<div class="row">
						<div class="col-md-6 col-sm-offset-3">
							<h2>Login</h2>
							<form method='POST'>
                                {% csrf_token %}
                                {{ form.as_p }}
								<div class="form-group text-center">
									<input type="submit" value="Login" class="btn btn-primary">
                                    <a href="{% url 'register' %}" class="btn btn-info">
                                        Register <i class="fa fa-arrow-right"></i>
                                    </a>
								</div>
							</form>
						</div>
					</div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load static %}
{% block navbar %} {% include 'base/navbar.html' %} {% endblock navbar %}
{% block content %}

    <div id="colorlib-contact">
		<div class="container">
			<div class="row">
                <div class="col-md-12 animate-box">
                    <h2>Health Insurance</h2>
                    <div class="row contact-info-wrap">
						<div class="col-md-3">
							<p><span><i class="icon-location"></i></span> 198 West 21th Street, <br> Suite 721 New York NY 10016</p>
						</div>
						<div class="col-md-3">
							<p><span><i class="icon-phone"></i></span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
						</div>
						<div class="col-md-3">
							<p><span><i class="icon-mail"></i></span> <a href="mailto:info@yoursite.com">info@yoursite.com</a></p>
						</div>
						<div class="col-md-3">
							<p><span><i class="icon-globe-outline"></i></span> <a href="#">yoursite.com</a></p>
						</div>
					</div>
                </div>
                <div class="col-md-12 animate-box">
					<div class="row">
						<div class="col-md-6">
							<h2>Register</h2>
							<form method='POST'>
                                {% csrf_token %}
                                {{ form.as_p }}
								<div class="form-group text-center">
									<input type="submit" value="Register" class="btn btn-primary">
								</div>
							</form>
						</div>
						<div class="col-md-6">
							<img class="img-responsive" src="{% static 'hmo-register.png' %}" alt="hmo-image"/>
                            <hr/>
                            <a href="{% url 'login' %}" class="btn btn-info btn-block">
                                <i class="fa fa-arrow-left"></i> Login
                            </a>
						</div>
					</div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}